---
# Supported Java Versions
# CentOS 7: latest, 11, 8, or 7
# CentOS 8: latest, 11, 8
# Ubuntu 18.04: 11 or 8
# Ubuntu 20.04: 14, 13, 11, or 8
kafka_java_version: 11
kafka_java_install: true

component_tag: saas_dev_env

# Confluent settings
confluent_version: 5.5
scala_version: 2.12



# Kafka connect settings
